---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nautilus
description: Opinionated Fedora Atomic niri image.
base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: 43

modules:
  - type: signing
  - from-file: snippets/niri-pkgs.yml
