---
# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json
type: dnf
install:
  packages:
    - audispd-plugins
    - cups-pk-helper
    - dracut-network
    - dracut-squash
    - glibc-minimal-langpack
    - grub2-efi
    - gstreamer1-plugin-openh264
    - gum
    - ifuse
    - jmtpfs
    - libcamera-v4l2
    - mobile-broadband-provider-info
    - NetworkManager-adsl
    - NetworkManager-openconnect
    - NetworkManager-openvpn
    - NetworkManager-ssh
    - NetworkManager-ssh-selinux
    - NetworkManager-strongswan
    - NetworkManager-vpnc
    - openconnect
    - passwd
    - shim
    - stalld
    - switcheroo-control
    - tuned
    - tuned-ppd
    - udisks2-lvm2
    - uxplay
    - vpnc
    - WALinuxAgent-udev
    - xdg-user-dirs
    - zlib
